HairSalon/Models/Client.cs
using System;
using System.Timers;
using System.Collections.Generic;
using System.Windows;
using System.Linq;
using System.ComponentModel.DataAnnotations;

namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId {get; set;}
    public string Name {get; set; }
    public int StylistId {get; set;} //foreign key
    // public List<Stylist> Stylists { get; set; } = new List<Stylist>(); //this doesn't work?
    public virtual Stylist Stylist { get; set; } //allow Client to store Stylist



  }
}

HairSalon/Models/ErrorViewModel.cs
namespace HairSalon.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon/Models/Stylist.cs
using System;
// using System.Timers;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// using System.Windows;
using System.Linq;

namespace HairSalon.Models
{
  public class Stylist
  {
    public int StylistId {get; set; }

    [Required]
    public string Name {get; set;}
    [Required]
    public string Specialty {get; set;}
    public virtual List<Client> Clients { get; set; } = new List<Client>(); //nav for ef core

    // public Stylist()
    // {
    //   Clients = new HashSet<Client>();
    // }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers;

public class ClientsController : Controller
{
  private readonly HairSalonContext _db;

  public ClientsController(HairSalonContext db)
  {
    _db = db;
  }

public IActionResult Index()
{
    var clients = _db.Clients.Include(c => c.Stylist).ToList(); //stylist MUST BE included for each client or the whole thing doesn't work
    return View(clients);
}

  [HttpGet]
  public IActionResult Create(int? stylistId)
  {
    // var stylists = _db.Stylists.Select(s => new { s.StylistId, s.Name});  //don't think this is necessary
    ViewBag.Stylists = new SelectList(_db.Stylists, "StylistId", "Name");//fixed outdated syntax. everything should be StylistId now
    return View();
  }

  [HttpPost]
  public IActionResult Create(Client client)
  {
    //debugging
    Console.WriteLine($"StylistId: {client.StylistId}");


    // if (ModelState.IsValid)
    // {
      _db.Clients.Add(client);
      _db.SaveChanges();
      return RedirectToAction("Index"); 
    // }
    // ViewBag.Stylists = new SelectList(_db.Stylists, "StylistId", "Name", client.StylistId);
    // return View(client);
  }

  public IActionResult Detail(int id)
  {
    var client = _db.Clients.Include(c => c.Stylist).FirstOrDefault(c => c.ClientId == id);
    if (client == null)
    {
      return NotFound();
    }
    return View(client);
  }
}

HairSalon/Controllers/HomeController.cs
//in homecontroller
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;

namespace HairSalon.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

HairSalon/Controllers/StylistsController.cs
//in stylistscontroller
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
// using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers;

public class StylistsController : Controller
{

  private readonly HairSalonContext _db;

  public StylistsController(HairSalonContext db)
  {
    _db = db;
  }

  [HttpGet]
  public IActionResult Create()
  {
    return View();
  }
  [HttpPost]
  public IActionResult Create(Stylist stylist)
  {
    if (ModelState.IsValid)
    {
      _db.Stylists.Add(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    return View(stylist);
  }

  public ActionResult Index()
  {
    var stylists = _db.Stylists.ToList();
    return View(stylists);
  }

  public IActionResult Detail(int id)
  {
    var stylist = _db.Stylists.Include(s => s.Clients).FirstOrDefault(s => s.StylistId == id);

    if (stylist == null)
    {
      return NotFound();
    }

    return View(stylist);
  }

  [HttpGet]
  public IActionResult Edit(int id)
  {
    var stylist = _db.Stylists.FirstOrDefault(s => s.StylistId == id);
    if (stylist == null)
    {
      return NotFound();
    }
    return View(stylist);
  }

  [HttpPost]
  public IActionResult Edit(Stylist stylist)
  {
    if (ModelState.IsValid)
    {
      _db.Update(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    return View(stylist);
  }

  [HttpGet]
  public IActionResult Delete(int id)
  {
    Stylist stylist = _db.Stylists.FirstOrDefault(s => s.StylistId == id);
    if (stylist == null)
    {
      return NotFound();
    }
    return View(stylist);
  }

  [HttpPost, ActionName("Delete")]
  public IActionResult DeleteConfirmed(int id)
  {
    Stylist stylist = _db.Stylists.Find(id);
    if (stylist != null)
    {
      _db.Stylists.Remove(stylist);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
    return NotFound();
  }
}

HairSalon/Views/Clients/Create.cshtml
@model HairSalon.Models.Client

@{
    ViewData["Title"] = "Add New Client";
}

<h2>@ViewData["Title"]</h2>

@if (!ViewData.ModelState.IsValid)
{
    <div class="alert alert-danger">
        <strong>There are some errors in your form:</strong>
        <ul>
            @foreach (var key in ViewData.ModelState.Keys)
            {
                @foreach (var error in ViewData.ModelState[key].Errors)
                {
                    <li>@error.ErrorMessage</li>
                }
            }
        </ul>
    </div>
}

@* Debugging ViewBag.Stylists *@
@* <h3>Stylists in ViewBag</h3>
<ul>
@foreach (var stylist in (SelectList)ViewBag.Stylists)
{
    <li>Id: @stylist.Value - Name: @stylist.Text</li>
}
</ul> *@

@using(Html.BeginForm())
{
   <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>

  <div class="form-group">
        @Html.LabelFor(model => model.StylistId, "Stylist")
        @Html.DropDownListFor(model => model.StylistId, (SelectList)ViewBag.Stylists, "Select a Stylist", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.StylistId, "", new { @class = "text-danger" })
    </div>

  <input type="submit" class="btn btn-primary" value="Add new client"/>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</div>

HairSalon/Views/Clients/Detail.cshtml
@model HairSalon.Models.Client

<h2>Client: @Model.Name</h2>

<div>
    <h4>Stylist:</h4>
    <p>@Model.Stylist.Name</p>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ClientId }) |
    @Html.ActionLink("Back to Stylist", "Details", "Stylists", new { id = Model.StylistId }, null)
</p>

HairSalon/Views/Clients/Index.cshtml
@model IEnumerable<HairSalon.Models.Client>

<h2>Clients</h2>

@if (Model.Any())
{
  <table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Stylist</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    
    @foreach (var client in Model)
    {
      <tr>
        <td>@Html.DisplayFor(modelItem => client.Name)</td>
        <td>@Html.DisplayFor(modelItem => client.Stylist.Name)</td>
        <td>
          @* @Html.ActionLink("Details", "Detail", new { id = client.ClientId }) *@
          @Html.ActionLink("View Details", "Detail", "Stylists", new { id = client.Stylist.StylistId }, null) |
          @Html.ActionLink("Edit", "Edit", new { id = client.ClientId }) |
          @Html.ActionLink("Delete", "Delete", new { id = client.ClientId })
        </td>
      </tr>
    }
  </tbody>
</table>
}
else
{
  <p>There are no current clients.</p>
}

<p>
  @Html.ActionLink("Add New Client", "Create", "Clients", null, new { @class = "btn btn-primary" })
</p>

HairSalon/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
  <p>Please use the nav bar to add or view Stylists and Clients</p>
</div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Hair Salon</title>
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="navbar">
        <a href="/stylists/index">Stylists</a>
        <a href="/clients/index">Clients</a>
        <a href="/stylists/create">Add Stylist</a>
        <a href="/clients/create">Add Client</a>
    </div>

    <div class="content">
        @RenderBody()
    </div>

    <footer>
        <p>&copy; @(DateTime.Now.Year) - Hair Salon</p>
    </footer>

    <script src="~/js/site.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@model HairSalon.Models.Stylist

<body>
    <div class="stylist-form">
        <h4>Add a new stylist</h4>
        @using (Html.BeginForm("Create", "Stylists", FormMethod.Post))
        {
            <div class="form-group">
                @Html.LabelFor(model => model.Name)
                @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Specialty)
                @Html.TextBoxFor(model => model.Specialty, new { @class = "form-control" })
            </div>

            <input type="submit" value="Add new stylist" class="btn btn-primary" />
        }
        <h4>Need to manage stylists? @Html.ActionLink("Go back to list", "Index")</h4>
    </div>
</body>

HairSalon/Views/Stylists/Delete.cshtml
@model HairSalon.Models.Stylist

@{
    ViewBag.Title = "Delete Stylist";
}

<h2>Delete Stylist</h2>

<h3>Are you sure you want to delete this stylist?</h3>
<div>
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd>@Html.DisplayFor(model => model.Name)</dd>

        <dt>Specialty</dt>
        <dd>@Html.DisplayFor(model => model.Specialty)</dd>
    </dl>

    @using (Html.BeginForm("Delete", "Stylists", FormMethod.Post))
    {
        @Html.HiddenFor(model => model.StylistId)
        <button type="submit" class="btn btn-danger">Delete</button>
        @Html.ActionLink("Cancel", "Index", null, new { @class = "btn btn-secondary" })
    }
</div>

HairSalon/Views/Stylists/Detail.cshtml
@model HairSalon.Models.Stylist

<h2>@Model.Name</h2>

<div>
    <h4>Specialty</h4>
    <p>@Model.Specialty</p>
</div>

<div>
    <h4>Clients</h4>
    @if (Model.Clients.Any())
    {
        <ul>
            @foreach (var client in Model.Clients)
            {
                <li>
                    @Html.ActionLink(client.Name, "Detail", "Clients", new { id = client.ClientId }, null)
                </li>
            }
        </ul>
    }
    else
    {
        <p>This stylist has no current clients.</p>
    }

</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.StylistId }) |
    @Html.ActionLink("Back to List", "Index")
</p>

HairSalon/Views/Stylists/Edit.cshtml
@model HairSalon.Models.Stylist

@{
    ViewBag.Title = "Edit Stylist";
}

<h2>Edit Stylist</h2>

@using (Html.BeginForm("Edit", "Stylists", FormMethod.Post))
{
    
    @Html.HiddenFor(model => model.StylistId)

    <div class="form-group">
        @Html.LabelFor(model => model.Name)
        @Html.TextBoxFor(model => model.Name, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Specialty)
        @Html.TextBoxFor(model => model.Specialty, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Specialty, "", new { @class = "text-danger" })
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>
}

<div>
    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn btn-secondary" })
</div>

HairSalon/Views/Stylists/Index.cshtml
@model IEnumerable<HairSalon.Models.Stylist>

<h2>Stylists</h2>

<p>
    @Html.ActionLink("Add New Stylist", "Create")
</p>
<table class="table">
    <tr>
        <th>Name</th>
        <th>Specialty</th>
        <th></th>
    </tr>
    @foreach (var stylist in Model)
    {
        <tr>
            <td>@Html.DisplayFor(modelItem => stylist.Name)</td>
            <td>@Html.DisplayFor(modelItem => stylist.Specialty)</td>
            <td>
                @Html.ActionLink("Detail", "Detail", new { id = stylist.StylistId }) |
                @Html.ActionLink("Edit", "Edit", new { id = stylist.StylistId }) |
                @Html.ActionLink("Delete", "Delete", new { id = stylist.StylistId })
            </td>
        </tr>
    }
</table>